In [2]:
import numpy as np
np.random.seed(42)

# Problem 1: Tạo hai ma trận 3x3 với các phần tử integer ngẫu nhiên từ 1 - 10.

In [3]:
mat1 = np.random.randint(1, 10, (3, 3))
mat1

array([[7, 4, 8],
       [5, 7, 3],
       [7, 8, 5]])

In [4]:
mat2 = np.random.randint(1, 10, (3, 3))
mat2

array([[4, 8, 8],
       [3, 6, 5],
       [2, 8, 6]])

# Problem 2: Thực hiện phép cộng phần tử, nhân từng phần tử, tích vô hướng với hai ma trận vừa được tạo.


In [5]:
sum_mat = np.add(mat1, mat2)
sum_mat

array([[11, 12, 16],
       [ 8, 13,  8],
       [ 9, 16, 11]])

In [6]:
mul_mat = np.multiply(mat1, mat2)
mul_mat

array([[28, 32, 64],
       [15, 42, 15],
       [14, 64, 30]])

In [7]:
matmul_mat = np.matmul(mat1, mat2)
matmul_mat

array([[ 56, 144, 124],
       [ 47, 106,  93],
       [ 62, 144, 126]])

# Problem 3: VIết hàm nhận vào một mảng Numpy, sau đó trả về tổng tất cả các phần tử của chúng


In [8]:
def sum_element(mat): 
    sum = np.sum(mat)
    return sum 

sum_element(mat1)

54